apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: yussufzoulfakar/frontend:1.0
          ports:
            - containerPort: 80
          env:
            - name: ARABIC_SERVICE_HOST
              value: "arabic-service"
            - name: ENGLISH_SERVICE_HOST
              value: "english-service"